config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  get 'simple_pages/about'
  get 'simple_pages/contact'
  post 'simple_pages/thank_you'
  get 'simple_pages/index'
  root 'simple_pages#landing_page'
  get 'payments/create'
  post 'payments/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders, only: [:index, :show, :create, :destroy]
  mount ActionCable.server => '/cable'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments
  validates :name, presence: true

  def self.search(search_term)
    if Rails.env.development?
      # Dev Mode (sqlite3)
      Product.where("name LIKE ?", "%#{search_term}%")
    else
      # Production or test mode (PostgreSQL)
      Product.where("name ilike ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end

  def average_rating
    comments.average(:rating).to_f
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: '/simple_pages/index' }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>

app/views/products/_form.html.erb
<div class="container">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
  <%= form.label :colour %><br>
  <%= form.text_field :colour %>
  </div>

  <div class="field">
  <%= form.label :price %><br>
  <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/products/_new_comment.html.erb

<% if signed_in? %>

    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <div class="form-group">
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    </div>
    <p>
      <div class="rating">
        <%= f.label :rating %><br>
      </div>
    </p>
    <p>
      <%= f.submit "Submit", class:"btn btn-danger red" %>
    </p>

  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-md-3">
  <div class="thumbnail">
    <%= link_to product do %>
    <%= image_tag(product.image_url, class: "img-responsive") if product.image_url%>
    <% end %>

    <p><strong>Product name:</strong><p><%= product.name %></p></p>
    <p><strong>Details:</strong><p><%= product.description %></p></p>
    <p><strong>Price €:</strong><p><%= product.price %></p></p>
  </div>

  <div class="product-buttons">
    <p><%= link_to 'Show', product %></p>
    <% if signed_in? && current_user.admin? %>
    <p><%= link_to 'Edit', edit_product_path(product) %></p>
    <p><%= link_to 'Delete', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>
<div class="container">
  <div class="edit-product">
    <div class="thumbnail">
      <%= render 'form', product: @product %>
      <%= link_to 'Show', @product %> |
      <%= link_to 'Back', products_path %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<h1>Currently available in our shop</h1>
  <% cache(cache_key_for_products) do %>
  <%= render @products %>
<% end %>
<% if @products.blank? %>
  <h4>There are no products containing this term. <%= params[:search] %></h4>
<% end %>

app/views/products/new.html.erb
<div class="container">
  <h1>Add New Product</h1>
  <div class="new-product">
    <div class="thumbnail">
      <%= render 'form', product: @product %>
      <%= link_to 'Back', products_path %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="show-product" data-product-id="<%= @product.id %>">
    <div class="thumbnail">
    <%# cache @product do %>
      <p><strong>Name:</strong>
        <%= @product.name %></p>

      <p><strong>Description:</strong>
        <%= @product.description %></p>

      <p><%= image_tag(@product.image_url, class: "img-responsive show-photo img-zoom", data_zoom_image: "@product.product_image.url")%></p>

        <p><strong>Price:</strong>
        <%= @product.price %></p>
<%# end %>

      <p>Average Rating: <div id="average-rating" class="rated" data-score="<%= @product.average_rating %>"></div> </p>
  <div class="pay-button">
      <!-- Stripe payments -->
      <%= form_tag "/payments/create" do %>
        <%= render partial: "shared/stripe_checkout_button" %>
        <%= hidden_field_tag(:product_id, @product.id) %>
      <% end %>

      <div>
        <%= render 'new_comment' %>
        <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
        <%= render 'comments' %>
      </div>

  </div>

</div>
<% if signed_in? && current_user.admin? %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<% end %>
</div>
</div>
<%= will_paginate @comments %>