config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  get 'simple_pages/about'
  get 'simple_pages/contact'
  post 'simple_pages/thank_you'
  get 'simple_pages/index'
  root 'simple_pages#landing_page'
  get 'payments/create'
  post 'payments/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders, only: [:index, :show, :create, :destroy]
  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">
    <title>Lotus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="page-wrap">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Lotus Art Berlin</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", simple_pages_index_path %></li>
          <li><%= link_to "About", simple_pages_about_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Orders", orders_path %></li>
          <li><%= link_to "Contact", simple_pages_contact_path %></li>
          <li>
            <div class="navbar-form" role="search">
              <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
              <%= form.text_field :q, id: 'q', value: params[:q] %>
              <div class="btn btn-link">
                <%= form.submit 'Search' %>
              </div>
                <% end %>
            </div>
          </li>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to('Login', new_user_session_path, class: "nav-link") %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <br>
    <% if notice %>
        <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p id="alert" class="alert alert-primary"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div><!-- end page-wrap-->
    <footer class="site-footer">
      &copy; 2018 Lotus Berlin
    </footer>
  </body>
</html>